---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: false

provisioner:
  name: chef_zero
  chef_client_path: /opt/local/bin/chef-client

# box: livinginthepast/smartos-base64-13.4.0
platforms:
  - name: smartos-13.4.0
    driver_config:
      box: livinginthepast/smartos-base64
      vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
      provision: true
      network:
       - ["forwarded_port", {guest: 3000, host: 3000}]
       - ["forwarded_port", {guest: 9985, host: 9985}]
       - ["forwarded_port", {guest: 8983, host: 8983}]
      customize:
        memory: 1024

suites:
  - name: replica
    run_list: 
      - recipe[modcloth-java::default]
      - recipe[modcloth-solr::replica]
    attributes:
      solr:
        newrelic:
          api_key: keykeykey
  - name: master
    run_list:
      - recipe[modcloth-java::default]
      - recipe[modcloth-solr::master]
    attributes:
      solr:
        newrelic:
          api_key: keykeykey
